<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>roy</string>
	</array>
	<key>name</key>
	<string>Roy</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.double-slash.roy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^#!.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.roy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"|'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.roy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"|'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.roy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.roy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.let.roy</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.roy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.roy</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.roy</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.roy</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.roy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(let)\s+(.+?)(\s+\(?\s*((.+?)(\s*:\s*(.+?))?)\s*\)?\s+)*(\s*:\s*(.+?))?\s*(=)</string>
			<key>name</key>
			<string>let.binding.roy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.lambda.roy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.roy</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.lambda.roy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\|λ)\s*(.+?)?\s*(-&gt;|→)</string>
			<key>name</key>
			<string>lambda.roy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.type.roy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.roy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(type)\s+([^=\s]+)\s*</string>
			<key>name</key>
			<string>type.roy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.data.roy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.roy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(data)\s+([^=\s]+)\s*</string>
			<key>name</key>
			<string>data.roy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.instance.roy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.roy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(instance)\s+([^=\s]+)\s*</string>
			<key>name</key>
			<string>instance.roy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.typeclass.roy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.roy</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.roy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(typeclass)\s+(.*?)\s+([^=\s]+)\s*</string>
			<key>name</key>
			<string>typeclass.roy</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#console</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.array.roy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.array.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(Array)\.(concat|constructor|every|filter|forEach|indexOf|isArray|join|lastIndexOf|length|map|pop|prototype|push|reduce|reduceRight|reverse|shift|slice|some|sort|splice|toSource|toString|unshift)\b</string>
					<key>name</key>
					<string>function.array.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.boolean.roy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.boolean.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(Boolean)\.(constructor|prototype|toSource|toString|valueOf)\b</string>
					<key>name</key>
					<string>function.boolean.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.date.roy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.date.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(Date)\.(constructor|getDate|getDay|getFullYear|getHours|getMilliseconds|getMinutes|getMonth|getSeconds|getTime|getTimezoneOffset|getUTCDate|getUTCDay|getUTCFullYear|getUTCHours|getUTCMilliseconds|getUTCMinutes|getUTCMonth|getUTCSeconds|getYear|now|parse|prototype|setDate|setFullYear|setHours|setMilliseconds|setMinutes|setMonth|setTime|setUTCDate|setUTCFullYear|setUTCHours|setUTCMilliseconds|setUTCMinutes|setUTCMonth|setUTCSeconds|setYear|toDateString|toGMTString|toISOString|toJSON|toLocaleDateString|toLocaleFormat|toLocaleString|toLocaleTimeString|toSource|toString|toTimeString|toUTCString|UTC|valueOf)\b</string>
					<key>name</key>
					<string>function.date.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.json.roy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.json.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(JSON)\.(parse|stringify)\b</string>
					<key>name</key>
					<string>function.json.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.math.roy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.math.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(Math)\.(E|LN2|LN10|LOG2E|LOG10E|PI|SQRT1_2|SQRT2)\b</string>
					<key>name</key>
					<string>constants.math.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.math.roy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.math.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(Math)\.(abs|acos|asin|atan|atan2|ceil|cos|exp|floor|imul|log|max|min|pow|random|round|sin|sqrt|tan|toSource)\b</string>
					<key>name</key>
					<string>function.math.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.number.roy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.number.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(Number)\.(MAX_VALUE|MIN_VALUE|NaN|NEGATIVE_INFINITY|POSITIVE_INFINITY)\b</string>
					<key>name</key>
					<string>constants.number.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.number.roy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.number.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(Number)\.(isFinite|isInteger|isNaN|prototype|toExponential|toFixed|toInteger|toLocaleString|toPrecision|toSource|toString|valueOf)\b</string>
					<key>name</key>
					<string>function.number.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.object.roy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.object.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(Object)\.(__count__|__defineGetter__|__defineSetter__|__lookupGetter__|__lookupSetter__|__noSuchMethod__|__parent__|__proto__|constructor|create|defineProperties|defineProperty|eval|freeze|getOwnPropertyDescriptor|getOwnPropertyNames|getPrototypeOf|hasOwnProperty|is|isExtensible|isFrozen|isPrototypeOf|isSealed|keys|preventExtensions|propertyIsEnumerable|prototype|seal|toLocaleString|toSource|toString|unwatch|valueOf|watch)\b</string>
					<key>name</key>
					<string>function.object.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.regexp.roy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.regexp.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(RegExp)\.(constructor|exec|global|ignoreCase|lastIndex|multiline|prototype|source|sticky|test|toSource|toString)\b</string>
					<key>name</key>
					<string>function.regexp.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.string.roy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.string.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(String)\.(charAt|charCodeAt|concat|constructor|contains|endsWith|fromCharCode|indexOf|lastIndexOf|length|localeCompare|match|prototype|quote|replace|search|slice|split|startsWith|substr|substring|toLocaleLowerCase|toLocaleUpperCase|toLowerCase|toSource|toString|toUpperCase|trim|trimLeft|trimRight|valueOf)\b</string>
					<key>name</key>
					<string>function.string.roy</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(decodeURI(Component)?|encodeURI(Component)?|eval|is(Finite|NaN)|parse(Float|Int))\b</string>
					<key>name</key>
					<string>support.function.roy</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Array|Boolean|Date|(Eval|Range|Reference|Syntax|Type|URI)?Error|Number|Object|RegExp|String)\b</string>
					<key>name</key>
					<string>support.type.roy</string>
				</dict>
			</array>
		</dict>
		<key>console</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.type.console.roy</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.function.console.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(console)\.(assert|debug|log|dir|error|group|groupCollapsed|groupEnd|info|log|time|timeEnd|trace|warn)\b</string>
					<key>name</key>
					<string>console.roy</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(false|true)\b</string>
					<key>name</key>
					<string>constant.language.boolean.roy</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(null|this|undefined)\b</string>
					<key>name</key>
					<string>constant.language.roy</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(data|let|type)\b</string>
					<key>name</key>
					<string>keyword.roy</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(bind|case|do|else|if|match|return|then)\b</string>
					<key>name</key>
					<string>keyword.control.roy</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(where|with)\b</string>
					<key>name</key>
					<string>keyword.other.roy</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b([+-]?\d+(\.\d+)?([Ee][+-]?\d+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.roy</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Magic numbers.</string>
					<key>match</key>
					<string>Infinity|NaN</string>
					<key>name</key>
					<string>support.constant.roy</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>=|&lt;-|-&gt;|←|→|⇒</string>
					<key>name</key>
					<string>assignment.operator.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\+|-|\*|/|%</string>
					<key>name</key>
					<string>binary.operator.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>!</string>
					<key>name</key>
					<string>unary.operator.roy</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.roy</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>type.operator.roy</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.roy</string>
	<key>uuid</key>
	<string>7943d659-7d53-422f-86a5-822900a41b82</string>
</dict>
</plist>
