<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>roy</string>
	</array>
	<key>name</key>
	<string>Roy</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.double-slash.roy</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^#!.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.roy</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"|'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.roy</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"|'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.roy</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.roy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.let.roy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.roy</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.roy</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.roy</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.roy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(let)\s+(.+?)(\s+\(?\s*((.+?)(\s*:\s+(.+?))?)\s*\)?\s+)*(\s*:\s+(.+?))?\s*=</string>
			<key>name</key>
			<string>let.binding.roy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.lambda.roy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.roy</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.lambda.roy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\|λ)\s*(.+?)?\s*(-&gt;|→)</string>
			<key>name</key>
			<string>lambda.roy</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.type.roy</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.roy</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(type)\s+(.+?)\s+=</string>
			<key>name</key>
			<string>type.roy</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(Array|Function|Int|Number|Object|String)\b</string>
					<key>name</key>
					<string>support.type.roy</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.boolean.roy</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b([+-]?\d+(\.\d+)?([Ee][+-]?\d+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.roy</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.roy</string>
	<key>uuid</key>
	<string>7943d659-7d53-422f-86a5-822900a41b82</string>
</dict>
</plist>
